### ISSUE TITLE
Spawn incident for every overlap and assign it to particular person

### ISSUE THREAD

**Issue by miiila** [apiaryio/pagerduty-overlap-checker#18]
Incidents are now distributed accordingly incident policy. It would be better to involve particular people, if possible.

**Comment by abtris** [comment]
can be this possible to send for example email to address that they have in PD?

**Comment by nadade** [comment]
#20

**Comment by nadade** [comment]
@abtris ad the second comment - I wouldn't go for more notifications; PD can be setup to send multiple types of notifications..
